name: shell commands
on:
 - push


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: multi line string
        run: |
          pwd
          node -v
          ls -a